### ISSUE TITLE
Plugwise-2.py. error message

### ISSUE THREAD

**Issue by TeRRia** [SevenW/Plugwise-2-py#11]
Hi SevenW,

I am not able to run Plugwise-2.py. This is the message I am getting on my raspberry:

rsync: link_stat "/home/pi/plugwise-2-log/datalog/2015/pwact/pwact-2015-11-22*.log" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
Traceback (most recent call last):
  File "Plugwise-2.py", line 1333, in <module>
    main=PWControl()
  File "Plugwise-2.py", line 163, in __init__
    self.circles.append(Circle(item['mac'], self.device, item))
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 332, in __init__
    self.reinit()
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 337, in reinit
    self._get_interval()
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 831, in _get_interval
    info = self.get_info()
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 558, in get_info
    resp = self._expect_response(PlugwiseInfoResponse, seqnr)
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 429, in _expect_response
    info("ONLINE  Circle '%s' after %d seconds." % (self.attr['name'], ts_now - self.last_seen))
KeyError: 'name'

I have check all my json files, they are Ok in terms of formatting. Any idea what could be the problem here ?

FYI - the "old" python-plugwise works fine for me, but I would really prefer to use your script as I would like to have it integrated within domoticz.

Kind regards,
Francois

**Comment by SevenW** [comment]
Hi,

I do not immediatelly see whats is going on here. Can you check that the name of the circles, and especially the string 'name' (lower case) is used as in here in pw-conf.json?

"name": "circle+",

The code that causes the exception is normally executed at every startup. So I suspect a configuration issue. So you see nothing obvious in your config file, can you please mail me your config files, so I can check?

SevenW

**Comment by TeRRia** [comment]
Thanks SevenW, changed pw-conf.json and pw-control.json to use lower string 'name' but unfortunately still facing same issue.

Adding the config files for your kind review:
[pw-control.json.txt](https://github.com/SevenW/Plugwise-2-py/files/41180/pw-control.json.txt)
[pw-hostconfig.json.txt](https://github.com/SevenW/Plugwise-2-py/files/41181/pw-hostconfig.json.txt)
[pw-conf.json.txt](https://github.com/SevenW/Plugwise-2-py/files/41179/pw-conf.json.txt)


Francois

**Comment by SevenW** [comment]
The way you specify the name was wrong. I have adapted the file, and 
this should work. Names like "tv" can have upper casing. It was about 
the attribute "name" that was missing.



Op 22-11-2015 om 23:30 schreef TeRRia:
>
> Thanks SevenW, changed pw-conf.json and pw-control.json to use lower 
> string 'name' but unfortunately still facing same issue.
>
> Adding the config files for your kind review:
> pw-control.json.txt 
> <https://github.com/SevenW/Plugwise-2-py/files/41180/pw-control.json.txt>
> pw-hostconfig.json.txt 
> <https://github.com/SevenW/Plugwise-2-py/files/41181/pw-hostconfig.json.txt>
> pw-conf.json.txt 
> <https://github.com/SevenW/Plugwise-2-py/files/41179/pw-conf.json.txt>
>
> Francois
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SevenW/Plugwise-2-py/issues/11#issuecomment-158810777>.
>



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

{"static": [
{"mac": "000D6F0001A5A0F6", "category": "misc", "name": "tv", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D32BE7", "category": "misc", "name": "amplifier", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D3384B", "category": "misc", "name": "canalplus", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D35788", "category": "misc", "name": "fibaro", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000C3B1E2", "category": "misc", "name": "telephonebase", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D3171F", "category": "misc", "name": "sonoskitchen", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D33778", "category": "misc", "name": "freebox", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000C3B1EF", "category": "misc", "name": "sonoslivingRoom", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000C3B1E9", "category": "misc", "name": "htpc", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D33B23", "category": "misc", "name": "freezerbasement", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D33B1F", "category": "misc", "name": "freezerkitchen", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D345F6", "category": "misc", "name": "washingmachine", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D33BA3", "category": "misc", "name": "plugpiano", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D3614D", "category": "misc", "name": "plugfrancoisdesk", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D33BA9", "category": "misc", "name": "plugcynthiaDesk", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D34001", "category": "misc", "name": "dishwasher", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D33B21", "category": "misc", "name": "nas", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F0000D3614B", "category": "misc", "name": "plugkitchenabovestairs", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F00023A5A8D", "category": "misc", "name": "heatpump1", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F00023A5AD7", "category": "misc", "name": "heatpump2", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"},
{"mac": "000D6F00039D828D", "category": "misc", "name": "heatpump3", "loginterval": "60", "always_on": "False", "production": "False", "location": "House"}
]}

**Comment by TeRRia** [comment]
Hello SevenW,

Sorry was abroad for a few days. Just back and tried the changes but still facing same issue exactly at the same place. Have you made the modifications directly in my files  (*.txt) ?

**Comment by SevenW** [comment]
No, they appeared in the issue tracker on github but you have to expand 
the reply. I copy the text in. It was about the syntax of the 
name-attribute.

{"static": [ {"mac": "000D6F0001A5A0F6", "category": "misc", "name": 
"tv", "loginterval": "60", "always_on": "False", "production": "False", 
"location": "House"}, {"mac": "000D6F0000D32BE7", "category": "misc", 
"name": "amplifier", "loginterval": "60", "always_on": "False", 
"production": "False", "location": "House"}, {"mac": "000D6F0000D3384B", 
"category": "misc", "name": "canalplus", "loginterval": "60", 
"always_on": "False", "production": "False", "location": "House"}, 
{"mac": "000D6F0000D35788", "category": "misc", "name": "fibaro", 
"loginterval": "60", "always_on": "False", "production": "False", 
"location": "House"}, {"mac": "000D6F0000C3B1E2", "category": "misc", 
"name": "telephonebase", "loginterval": "60", "always_on": "False", 
"production": "False", "location": "House"}, {"mac": "000D6F0000D3171F", 
"category": "misc", "name": "sonoskitchen", "loginterval": "60", 
"always_on": "False", "production": "False", "location": "House"}, 
{"mac": "000D6F0000D33778", "category": "misc", "name": "freebox", 
"loginterval": "60", "always_on": "False", "production": "False", 
"location": "House"}, {"mac": "000D6F0000C3B1EF", "category": "misc", 
"name": "sonoslivingRoom", "loginterval": "60", "always_on": "False", 
"production": "False", "location": "House"}, {"mac": "000D6F0000C3B1E9", 
"category": "misc", "name": "htpc", "loginterval": "60", "always_on": 
"False", "production": "False", "location": "House"}, {"mac": 
"000D6F0000D33B23", "category": "misc", "name": "freezerbasement", 
"loginterval": "60", "always_on": "False", "production": "False", 
"location": "House"}, {"mac": "000D6F0000D33B1F", "category": "misc", 
"name": "freezerkitchen", "loginterval": "60", "always_on": "False", 
"production": "False", "location": "House"}, {"mac": "000D6F0000D345F6", 
"category": "misc", "name": "washingmachine", "loginterval": "60", 
"always_on": "False", "production": "False", "location": "House"}, 
{"mac": "000D6F0000D33BA3", "category": "misc", "name": "plugpiano", 
"loginterval": "60", "always_on": "False", "production": "False", 
"location": "House"}, {"mac": "000D6F0000D3614D", "category": "misc", 
"name": "plugfrancoisdesk", "loginterval": "60", "always_on": "False", 
"production": "False", "location": "House"}, {"mac": "000D6F0000D33BA9", 
"category": "misc", "name": "plugcynthiaDesk", "loginterval": "60", 
"always_on": "False", "production": "False", "location": "House"}, 
{"mac": "000D6F0000D34001", "category": "misc", "name": "dishwasher", 
"loginterval": "60", "always_on": "False", "production": "False", 
"location": "House"}, {"mac": "000D6F0000D33B21", "category": "misc", 
"name": "nas", "loginterval": "60", "always_on": "False", "production": 
"False", "location": "House"}, {"mac": "000D6F0000D3614B", "category": 
"misc", "name": "plugkitchenabovestairs", "loginterval": "60", 
"always_on": "False", "production": "False", "location": "House"}, 
{"mac": "000D6F00023A5A8D", "category": "misc", "name": "heatpump1", 
"loginterval": "60", "always_on": "False", "production": "False", 
"location": "House"}, {"mac": "000D6F00023A5AD7", "category": "misc", 
"name": "heatpump2", "loginterval": "60", "always_on": "False", 
"production": "False", "location": "House"}, {"mac": "000D6F00039D828D", 
"category": "misc", "name": "heatpump3", "loginterval": "60", 
"always_on": "False", "production": "False", "location": "House"} ]}

Op 27-11-2015 om 0:32 schreef TeRRia:
>
> Hello SevenW,
>
> Sorry was abroad for a few days. Just back and tried the changes but 
> still facing same issue exactly at the same place. Have you made the 
> modifications directly in my files (*.txt) ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SevenW/Plugwise-2-py/issues/11#issuecomment-160004588>.
>



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by TeRRia** [comment]
Thank you. Moving forward but unfortunately getting a new error message now:
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
Traceback (most recent call last):
  File "Plugwise-2.py", line 1333, in <module>
    main=PWControl()
  File "Plugwise-2.py", line 154, in __init__
    sconf = json.load(open(self.staticconfig_fn))
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 39 column 1 - line 40 column 1 (char 3382 - 3384)

Francois

**Comment by SevenW** [comment]
This is a syntax error in json. Could be my mistake. Can you check with 
lint as in the instructions?

SevenW

Op 27-11-2015 om 13:51 schreef TeRRia:

**Comment by TeRRia** [comment]
you were right, it all works now, perfect and thank you for the support SevenW!

**Comment by SevenW** [comment]
Removed .json files for privacy reasons.
