### ISSUE TITLE
Sending messages to Domoticz via MQTT instead of HTTP JSON

### ISSUE THREAD

**Issue by frankhommers** [SevenW/Plugwise-2-py#17]
I don't know if it's possible, but I think it would be more efficient if the Node-Red Domoticz script would send the data back to domoticz via MQTT. That would be more efficient because it won't be seperate HTTP requests.

**Comment by pepijng** [comment]
Yes it's possible to to this but there are also some reason why it's not there:

- MQTT does not support RAW devices, so the Plugwise devices will not be created automatically, so every device must be added as a virtual device and the Node-RED to be modified with the correct device ID's.

- There are some stability issues with the MQTT hardware device in Domoticz
- When I created the initial Node-RED flow MQTT was not available.

**Comment by frankhommers** [comment]
This issue might still be relevant for others, but I don't need it anymore since I have moved to Z-Wave ;-)
