### ISSUE TITLE
When I change the Switch to On the Schedule goes to Off always

### ISSUE THREAD

**Issue by frankhommers** [SevenW/Plugwise-2-py#18]
Is this behaviour the way it should be?

Maybe I don't understand this, what is supposed to be the meaning of the Schedule On and Off switch?

**Comment by SevenW** [comment]
This is behaviour as intended. When the "Switch" is operated directly, 
the "Schedule" is switched off. In other words. The Schedule is inactive 
once the circle is switched manually, and for further time schedule 
operation, the Schedule needs to be activated again (Schedule = On).

I hope this clarifies it a bit.

SevenW

Op 1-1-2016 om 21:22 schreef Frank Hommers:
>
> Is this behaviour the way it should be?
>
> Maybe I don't understand this, what is supposed to be the meaning of 
> the Schedule On and Off switch?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SevenW/Plugwise-2-py/issues/18>.
>



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by frankhommers** [comment]
It clarifies it a bit. But how do I achieve the following: I want to switch a device on using a standby killing schedule. Let's say, if the wattage drops below 25w I want to switch it off automatically. Plugwise Source did allow this. 

A switch 'On' while keeping the schedule 'On'.

**Comment by SevenW** [comment]
In the schedules you can just program the 25 watt treshold, by typing 25 
in the cell in the schedule editor. Then the schedule can stay on.

The thing that I have never understood very well is how to turn 
something on again that has been turned off by the standby killer.

In plugwise 2 py, this can be achieved by to steps:
1. Switch = ON
2. Schedule is ON
The second is required to resume schedule operation.

What may be missing is a third switch command (next to Switch and 
Schedule) which would have semantics like 
"SwitchWhileScheduleKeepsBeingActive", or "OverrideScheduleFor15Mintues".
Is that what you are looking for?

SevenW



Op 3-1-2016 om 19:20 schreef Frank Hommers:
>
> It clarifies it a bit. But how do I achieve the following: I want to 
> switch a device on using a standby killing schedule. Let's say, if the 
> wattage drops below 25w I want to switch it off automatically. 
> Plugwise Source did allow this.
>
> A switch 'On' while keeping the schedule 'On'.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SevenW/Plugwise-2-py/issues/18#issuecomment-168526743>.
>



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by frankhommers** [comment]
Yes! I mean "SwitchWhileScheduleKeepsBeingActive". This is the default behaviour in Plugwise Source.

**Comment by SevenW** [comment]
Can you specify this function in more detail? 

So it is a temporary override of the schedule. When does the schedule
resume? 

At its next 15-minute block? 

What do you expect to happen when the schedule specifies the circle to
be off for the coming few hours, and the override switch turns it on?
How long would it stay on? 

SevenW

**Comment by frankhommers** [comment]
In source you can make schedules based on hours, quarters or half-hours. When you have assigned a schedule to a device and you switch it on, it would go off at the next quarter, hour or half-hour when the power usage drops below the threshold.

I would prefer to have the on/grace period to be a per-device setting. So for instance I would like to turn my dishwasher on for at least 90 minutes regardless of the powerusage, and after that I would like to keep it on if the powerusage is above the threshold and turn off when it's below the threshold. 

That period (90 minutes) is different for other devices.

**Comment by frankhommers** [comment]
This issue might still be relevant for others, but I don't need it anymore since I have moved to Z-Wave ;-)
