### ISSUE TITLE
Reading of circle buffers

### ISSUE THREAD

**Issue by bergje4** [SevenW/Plugwise-2-py#20]
Hi,

I am running into an issue where the circle buffers are read (and saved) for only 7 out of 19 plugs. The plugs dat do get their buffers read are the first 7 in my configuration.

At first I thought my plug wise network might not be okay, but I receive measurements for all plugs. Furthermore the plugs that do work are all over the house.

The pwlastlog.log file displays values and information on the first 7 lines, the other lines just display zeroes after the mac addresses.

Am I doing something wrong? Is there a way to force the other buffers to be read as well?

Thanks for any help!

Kind regards,

berg

**Comment by SevenW** [comment]
Could you send me the logfiles. Please mail them to user info at the 
domain name of my main website.
https://www.sevenwatt.com/
SevenW

Op 27-3-2016 om 19:27 schreef bergje4:
>
> Hi,
>
> I am running into an issue where the circle buffers are read (and 
> saved) for only 7 out of 19 plugs. The plugs dat do get their buffers 
> read are the first 7 in my configuration.
>
> At first I thought my plug wise network might not be okay, but I 
> receive measurements for all plugs. Furthermore the plugs that do work 
> are all over the house.
>
> The pwlastlog.log file displays values and information on the first 7 
> lines, the other lines just display zeroes after the mac addresses.
>
> Am I doing something wrong? Is there a way to force the other buffers 
> to be read as well?
>
> Thanks for any help!
>
> Kind regards,
>
> berg
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/SevenW/Plugwise-2-py/issues/20>
>



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by SevenW** [comment]
I received the logging. Thanks. I think your analysis is accurate. This was a use case that I never considered. Having monitoring=yes, and loginterval 1 minute, indeed can cause this behaviour, as at most one circles buffers are read every ten seconds (to make the system responsive for switch commands). After a minute, the first circle has a new datum point, so is served first again. The strategy should indeed be modified by not testing the first circle again for new data, but proceeding at the next (unread) circle.

I can easily fix this, but it may take a few days before I can repair it.

SevenW

**Comment by SevenW** [comment]
A few days might have been an underestimation. But I fixed it today, and it is now on the develop stream. It will soon be merged into master.

**Comment by SevenW** [comment]
Solution available in master.
