### ISSUE TITLE
intermittent weird readings

### ISSUE THREAD

**Issue by gruijter** [SevenW/Plugwise-2-py#24]
I get intermittent weird readings. I know I have a 'difficult' network with 12 circles in a concrete house. But with the source software the readings were always stable. And I'm running it from the same pc, so no change in hardware or location or the usb plug. Is there any chance you can further improve readings from weak networks?

**Comment by SevenW** [comment]
Please send me a logfile and maybe some datalogging files where I can see what you mean. You could mail me at user info at my domain. Click user SevenW to figure out my domain.

**Comment by gruijter** [comment]
@SevenW found a problem with one of my circles giving a different output than he ever came across. This is now quick-fixed on my system, but needs a permanent change in the GitHub version.

**Comment by SevenW** [comment]
In the end there appeared to be two issues:
1. The application crashed on reading historic buffers with a layout I had not seen before. This caused the web UI showing some values recorded a long time ago.
2. One circle, which was used for PV solar energy, gave negative readings, while another one behaved normally. Also in plugwise source this circle gave negative readings, but source corrected it for reports. My hypothesis is that occasionally a circle is internally wired in a different way. I introduced a configuration option "reverse_pol": "True" in pw-conf.json to optionally negate power readings. 

Soon the solutions will be available in master.

**Comment by SevenW** [comment]
Solutions available in master.

**Comment by gruijter** [comment]
Great! I will test this asap.
