### ISSUE TITLE
Cannot get switch device to work

### ISSUE THREAD

**Issue by heggink** [SevenW/Plugwise-2-py#46]
Hope you can give me a hand: For each switch, I have 6 devices in Domoticz (A0-F0 with submac). The power readings and consumptions are working great but I get an error as soon as I try to switch on/off the B) device:
MySensors: Light command received for unknown node_id: 213
I have the following device:
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 42,
         "HardwareName" : "VirtualPlugwise-2-py",
         "HardwareType" : "MQTT Client Gateway with LAN interface",
         "HardwareTypeVal" : 43,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "B05528D5",
         "Image" : "Light",
         "IsSubDevice" : true,
         "LastUpdate" : "2017-11-26 13:07:10",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "ID1_5528D5",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "823"
      },
Any idea what's wrong? For now, I am switching the devices through mqtt messages which works OK but not ideal. Thx!!

**Comment by SevenW** [comment]
MQTT between domoticz and Plugwise-2-py is the only way to switch. MQTT is just the glue between the two applications.

Can you provide some logging from Plugwise-2py on such a switch event? Preferably also some MQTT messages logged from the communication between the two apps. Can be done with nodered, or a may be able to provide a python script that subscribes to MQTT to monitor messages.

SevenW

**Comment by heggink** [comment]
I'll try to get some logging but it seems like there is nothing happening from Domoticz to p2py. The devices get created when messages come in and I enables "allow new devices for 5 mins" in Domoticz. From them onwards all comms from p2py to domoticz is fine but domoticz errors trying to send something back and references a  device type MySensors with an unknown node on the domoticz logs. I am pretty sure it does not send anything to mqtt.

**Comment by heggink** [comment]
It's a domoticz error. Nopthing gets sent to mqtt from domoticz as it errors indeed. Checked and nothing happening from domo->p2py.
http://www.domoticz.com/forum/viewtopic.php?f=6&t=20627
has the data

**Comment by dorenberg** [comment]
I have the same issues. However, power off of a circle works in Domoticz, but turning it on again does not. I get a domoticz error of command not recognized (or something like that).

**Comment by SevenW** [comment]
@heggink: Does this problem persists? I can't reproduce. I can switch circles on and off from domoticz, using the mqtt domoticz/out topic in node-red. I have domoticz version 3.8153. Do you have a newer version?

**Comment by heggink** [comment]
Unfortunately yes. I run the latest beta myself (couple of issues in 8153 that caused my system to run out of memory). I pretty much decommissioned most of the plugs because of (ir)regular connection issues causing plugs to get unresponsive and me to unplug the circle+ and usb stick too often.

Shame because I have 11 plugs altogether. Not sure if the stick is faulty and needs replacing. I intend to flog them on ebay once my plugin hybrid car is replaced (back to diesel as no electric supply in NL for at least 9 more months) and I no longer need to expense its power consumption.

Thanks for the great work so far. Worked really well for quite a while and even the on/off switching was workable through a workaround (just issued mqtt commands fro the script line in the device def).

Much obliged (as the americans say ;-)).

**Comment by SevenW** [comment]
Regarding your plugs being decommissioned. Was it that the used to work, but connectivity degraded over time, without obvious reason? You could contact bwired to ask for his experiences.

**Comment by CorSpruit** [comment]
I have exactly the same situation with synology, multiple switches startend with A, B, C etc.
Wicht one should I select and how can I switch with On action or Off action

**Comment by SevenW** [comment]
The Normal light switch is the device where the ID starts with B.

**Comment by CorSpruit** [comment]
Where  can I find a script for On/Off Action to switch via MQTT

Op 10 mrt. 2018 09:50 schreef "Seven Watt" <notifications@github.com>:
