### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by edwindarter** [SevenW/Plugwise-2-py#50]
After a power failure plugwise2py stopped working

I cant start plugwise 2py 
And get this error:

rsync -aXuq /home/pi/datalog/2018/pwact/pwact-2018-02-22*.log /tmp/2018/pwact/
rsync: link_stat "/home/pi/datalog/2018/pwact/pwact-2018-02-22*.log" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
Traceback (most recent call last):
File "Plugwise-2.py", line 1467, in <module>
main=PWControl()
File "Plugwise-2.py", line 126, in __init__
self.device = Stick(port, timeout=1)
File "/home/pi/Plugwise-2-py/plugwise/api.py", line 60, in __init__
self.init()
File "/home/pi/Plugwise-2-py/plugwise/api.py", line 65, in init
self.send_msg(msg)
File "/home/pi/Plugwise-2-py/plugwise/api.py", line 93, in send_msg
resp = self.expect_response(PlugwiseAckResponse)
File "/home/pi/Plugwise-2-py/plugwise/api.py", line 186, in expect_response
msg = self._recv_response(retry_timeout)
File "/home/pi/Plugwise-2-py/plugwise/api.py", line 142, in _recv_response
raise TimeoutException("Timeout while waiting for response from device")
plugwise.exceptions.TimeoutException: Timeout while waiting for response from device
How can i solve this?

**Comment by MagnusThome** [comment]
Check that your USB Plugwise Stick still is available in the OS? Like:

find /sys/bus/usb/devices/usb*/ -name dev
or
lsusb
or
sudo dmesg | grep tty|grep USB

**Comment by SevenW** [comment]
Indeed try to see whether the usb device is there.
You could try to unplug and plug the stick. Sometimes it recovers then, but not always. Check dmesg to see whether ttyUSB0 is back (or whatever usb device it is on your system).

Otherwise reboot youtr machine and see whether it properly starts.

**Comment by edwindarter** [comment]
Did what you told,
And its working again 
Thank you very much!!!!!
