### ISSUE TITLE
Just an observation FYI: If a handfull of Circles are missing the rest can't be controlled anymore

### ISSUE THREAD

**Issue by MagnusThome** [SevenW/Plugwise-2-py#51]
Normally you'd not have a whole bunch of Circles missing so it's not really a problem. 

But I've noted that if enough Circles are offline/missing you can't control the ones that still are online.

**Comment by SevenW** [comment]
That is indeed a known problem. It would require me to make the program multi-threaded. That is possible, but also comes with risk and a period to stabilize the code. Until now I did not want to invest in it. Some years back I made several improvements in responsiveness.

In the case of the initial run, where it is reading out large numbers of historic buffer addresses, then it can be extremely unresponsive but that usually cures after several hours
