### ISSUE TITLE
MQTT password

### ISSUE THREAD

**Issue by w2cker** [SevenW/Plugwise-2-py#53]
I am using Hassbian on raspberry Pi. Everything is working fine but I have to allow anonymous access to Mosquito. Can I set the MQTT username and password in the config?

**Comment by SevenW** [comment]
Yes, the pw-hostconfig file had two keywords for it. See this file, and check the github text on the main page. It should be explained.

Verstuurd vanaf mijn iPhone

**Comment by w2cker** [comment]
Thank you. I did find the keyword in the python script.
