### ISSUE TITLE
No input in pw-logger.log

### ISSUE THREAD

**Issue by meden199** [SevenW/Plugwise-2-py#55]
Plugwise-2-py is running on my Pi3 but after running a night no data has show up.
After looking in the pw-logger.log file I noticed it was empty.

I did run tail -f /home/pi/pwlog/pw-logger.log but it keep empty.

**Comment by SevenW** [comment]
A bit late form my side. 
I suspect Plugwise-2-py is actually not running, but crashes just after starting.
What you could do is start Plugwsie-2-py from a command line, interactively and see what crashdump you get.
The dump is also stored in a nohup utput ile, I think in the folder of the tmp path, as configred in host-config file.
