### ISSUE TITLE
Plugwise error

### ISSUE THREAD

**Issue by edwindarter** [SevenW/Plugwise-2-py#57]
rsync: link_stat "/home/pi/datalog/2018/pwact/pwact-2018-09-10*.log" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

**Comment by SevenW** [comment]
This is not an error for Plugwise2py, but I could not get easily suppress this linux rsync command message. Please ignore.
