### ISSUE TITLE
Plugwise WLAN interface instead of serial?

### ISSUE THREAD

**Issue by SjeesDeBees** [SevenW/Plugwise-2-py#58]
What if i would like to use this brilliant piece of scripting for reading my Plugwise Smile and displaying the parameters on Domoticz via MQTT (so far so good), but not using the serial interface of the Smile, but using the WLAN interface? 
I have some python experience, but not a lot, otherwise i would have tried myself.
(I am running Domoticz on a Raspberry 3B+ 2018 w Raspbian Stretch)
Can one of you suggest a solution or direction?

**Comment by SevenW** [comment]
Plugwise2py is for 80% about handling the zigbee communication through the stick. The Stretch and Smile offer a completely different API. I don't think adapting plugwise2py is the way forward.

Specifically for Domoticz, someone has made a linux script to connect the Stretch to Domoticz. This may also work for the smile.

https://www.domoticz.com/forum/viewtopic.php?t=8096
https://www.domoticz.com/forum/viewtopic.php?t=12239

I general I am surprised that support for Smile and Stretch is quite low in the open source domotica community now that I did some googling.

**Comment by SjeesDeBees** [comment]
Same thought about the lack of support here, although i did not ask Plugwise themselves. Normally i find most i need on github or tweakers(nl).

I found the bash scripts as well, but thought of them as for interfacing with the serial port, and i am a little into python, but not into Bash at all. So i guess i should learn more about both myself to get it going.

Thanks sofar.
