### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' 

### ISSUE THREAD

**Issue by MagnusThome** [SevenW/Plugwise-2-py#59]
Hi!

Do you have any idea what this can be?

```
Oct 06 16:00:29 srv python[5492]:   File "/home/user/Plugwise-2-py/Plugwise-2.py", line 170, in __init__
Oct 06 16:00:29 srv python[5492]:     self.circles.append(Circle(item['mac'], self.device, item))
Oct 06 16:00:29 srv python[5492]:   File "/home/user/Plugwise-2-py/plugwise/api.py", line 390, in __init__
Oct 06 16:00:29 srv python[5492]:     self.reinit()
Oct 06 16:00:29 srv python[5492]:   File "/home/user/Plugwise-2-py/plugwise/api.py", line 408, in reinit
Oct 06 16:00:29 srv python[5492]:     error("OFFLINE Circle '%s' during initialization Error: %s" % (self.attr['name'], str(reason))
Oct 06 16:00:29 srv python[5492]: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 49: ordinal not in ra
Oct 06 16:00:29 srv systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
Oct 06 16:00:29 srv systemd[1]: plugwise.service: Unit entered failed state.
Oct 06 16:00:29 srv systemd[1]: plugwise.service: Failed with result 'exit-code'.
```

**Comment by SevenW** [comment]
It is indeed the character ä.

It crashes when the program tries to lof an error message to the logfile, with a circle name containing the specific character. Obviously this should not break. I need to check the code and see if this specific line of code is missing some conversion. I think I have this repaired in some places before.

**Comment by SevenW** [comment]
Could you check the encoding you are using?
open a console / ssh window
type:
python
and in interactive python:
import sys
sys.stdout.encoding

and send me the result?

**Comment by MagnusThome** [comment]
UTF-8

**Comment by MagnusThome** [comment]
Just FYI:

I subscribe to the MQTT topics from plugwise and a Mosquitto server in python with paho.mqtt.client and dump this data as is into MySQL. Then I collect this data in MySQL with php and display on a webpage. To get the correct swedish characters I have to do this in php:

$name = mb_convert_encoding($plugname, 'utf-8', 'iso-8859-1');

**Comment by MagnusThome** [comment]
Did this on line 408

`error("OFFLINE Circle '%s' during initialization Error: %s" % (self.attr['name'].decode('iso-8859-1').encode('utf8'), str(reason)))`

**Comment by MagnusThome** [comment]
> Did this on line 408
> 
> `error("OFFLINE Circle '%s' during initialization Error: %s" % (self.attr['name'].decode('iso-8859-1').encode('utf8'), str(reason)))`

Hmmm... no, didn't help

**Comment by MagnusThome** [comment]
> Had the same crash with identical error message in another place in the code too, line 838:
> `error("Error in ten_seconds(): %s" % (reason,))`

Didn't think of it first... but it's NOT the name, it's the reason here!!

**Comment by SevenW** [comment]
I think the %-formatting just can't deal with unicode. And the problem is that it is everywhere in the code.

I am currently trying out a few things to see what would be the easiest fix.

**Comment by SevenW** [comment]
The last reported error occurs because the exception reason contains the circle name in a formatted string. This formatting happens in raising the exception. It happens here, and in two places just below this line:
https://github.com/SevenW/Plugwise-2-py/blob/6f3325cf683cebe3fcc58e0d5db3dedd1b5cb593/plugwise/api.py#L490

Now the simpler temporary solution might be to explicitly make the circle name attribute a byte string, utf-8 encoded.

Testing can be made efficient by adding an unconditional logging of circle names at startup.

Going to check this idea now.

**Comment by MagnusThome** [comment]
Ah!! So it _was_ still the name hehe.

I've temporarily just edited out the %s stuff so it doesn't crash. I'm running the system live now in my country house. Very very nice!

**Comment by SevenW** [comment]
What is your log level? If it is error, please put it to info. I expect info logging to cause the UnicodeError during startup. OTOH I would expect the info logging call always to be made, so why doesn't it crash there unconditionally? Weird.

See line https://github.com/SevenW/Plugwise-2-py/blob/6f3325cf683cebe3fcc58e0d5db3dedd1b5cb593/Plugwise-2.py#L173

Could you add below line 173 the following (needs to have same indentation as info logging!)
`            self.circles[-1].attr['name'] = self.circles[-1].attr['name'].encode('utf-8')

And add as line 2 in same file (Plugwise-2.py) this:
`# -*- coding: utf-8 -*-`

**Comment by MagnusThome** [comment]
Added the two lines above and returned my three edited lines to original.

Logging was at info already

Restarted, no crash so far but normally it can take many many hours before it crashes

**Comment by MagnusThome** [comment]
Not there now

**Comment by MagnusThome** [comment]
I have one that is out of the network currently, I could rename that one and restart?

**Comment by SevenW** [comment]
This log file is recorded after you have edited the two lines?
At least it logs nicely all Swedish characters, but maybe it already did before the change.

I can't really grasp why the info logging is OK, while the error logging cause a crash.

Maybe your last suggestion is indeed a test. However the program might be robust for this. You can try. Use an ä. This is known to cause failures.

**Comment by MagnusThome** [comment]
Changed the name and BOOM :-)

```
Oct 24 22:34:04 debianlandet python[1955]:   File "/home/sommar/Plugwise-2-py/plugwise/api.py", line 409, in reinit
Oct 24 22:34:04 debianlandet python[1955]:     error("OFFLINE Circle '%s' during initialization Error: %s" % (self.attr['name'], str(reason)))
Oct 24 22:34:04 debianlandet python[1955]: UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-53: ordinal not in range(128)
Oct 24 22:34:04 debianlandet systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
O
```

**Comment by MagnusThome** [comment]
testing individual characetrs now. First test was åäö/ÅÄÖ

**Comment by MagnusThome** [comment]
å - fail u'\xe5'
ä - fail u'\xe4'
ö - fail u'\xf6'

**Comment by SevenW** [comment]
The utf-8 conversion did not happen yet in this specific situation. Lets try conversion in a different place:

https://github.com/SevenW/Plugwise-2-py/blob/6f3325cf683cebe3fcc58e0d5db3dedd1b5cb593/plugwise/api.py#L353

Under this line (I suspect it is line 354 as you may have made an edit somewhere), add this, same indentation again:
`   self.attr['name'] = self.attr['name'].encode('utf-8')`

**Comment by SevenW** [comment]
Note that this is another file: api.py

**Comment by MagnusThome** [comment]
Yup, edited api.py, still:

```
Oct 24 22:45:23 debianlandet python[2623]:   File "/home/sommar/Plugwise-2-py/Plugwise-2.py", line 175, in __init__
Oct 24 22:45:23 debianlandet python[2623]:     self.circles[-1].attr['name'] = self.circles[-1].attr['name'].encode('utf-8')
Oct 24 22:45:23 debianlandet python[2623]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Oct 24 22:45:23 debianlandet systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
O
```

**Comment by MagnusThome** [comment]
Should I add the utf8 in the header in more files?

**Comment by SevenW** [comment]
No

**Comment by SevenW** [comment]
But I see we did well now, as the exception is now at a different line. Please comment out line 175 in Plugwise-2.py now.

**Comment by MagnusThome** [comment]
No crash so far

**Comment by MagnusThome** [comment]
I made this to be able to do quick edits in just one place and copy over the changes to pw-control.json

[makecontrol.zip](https://github.com/SevenW/Plugwise-2-py/files/2512302/makecontrol.zip)

**Comment by SevenW** [comment]
What reads the line off logging concerning this not connected circle. The line with "ERROR - OFFLINE Circle during initialization"?

I expect this crash of this specific logging to be solved, although the name may come from the direct circle name logging and the TimeoutExcpetion in the variable reason.

**Comment by MagnusThome** [comment]
Now after removing line 175 it looks like this

```
2018-10-24 22:44:58,819 - pw-logger - ERROR - OFFLINE Circle 'BruåäöÅÄÖnnpump' during initialization Error: Timeout while waiting for response from circle 'BruåäöÅÄÖnnpump'
2018-10-24 22:45:23,223 - pw-logger - ERROR - OFFLINE Circle 'BruåäöÅÄÖnnpump' during initialization Error: Timeout while waiting for response from circle 'BruåäöÅÄÖnnpump'
2018-10-24 22:46:49,380 - pw-logger - ERROR - OFFLINE Circle 'BruåäöÅÄÖnnpump' during initialization Error: Timeout while waiting for response from circle 'BruåäöÅÄÖnnpump'
2018-10-24 22:50:08,127 - pw-logger - ERROR - OFFLINE Circle 'BruåäöÅÄÖnnpump' during initialization Error: Timeout while waiting for response from circle 'BruåäöÅÄÖnnpump'
2018-10-24 22:50:18,519 - pw-logger - ERROR - OFFLINE Circle 'Boden utebelysning' during initialization Error: Timeout while waiting for response from circle 'Boden utebelysning'
2018-10-24 22:54:14,984 - pw-logger - ERROR - OFFLINE Circle 'BruåäöÅÄÖnnpump' during initialization Error: Timeout while waiting for response from circle 'BruåäöÅÄÖnnpump'
2018-10-24 22:54:49,754 - pw-logger - ERROR - OFFLINE Circle 'BruåäöÅÄÖéèüÉônnpump' during initialization Error: Timeout while waiting for response from circle 'BruåäöÅÄÖéèüÉônnpump'

```

**Comment by SevenW** [comment]
Great! This one is fully fixed.

The other situation is not tested yet, but I expect it is solved as well:
> Had the same crash with identical error message in another place in the code too, line 838:
> `error("Error in ten_seconds(): %s" % (reason,))`

Just let it run for a while and then search logfile for  "Error in ten_seconds" and verify it is logged once in a while with one of the suspect characters.

I am 90% confident!

**Comment by MagnusThome** [comment]
thumbs up!

So leave line 175 commented out and let it run?

**Comment by MagnusThome** [comment]
I noticed that when I was testing individual characters one by one and it crashed on each it managed to print out once per run before crashing later in the code:

```
2018-10-24 22:39:36,041 - pw-logger - DEBUG - Received an error status '00E1' from circle 'Bruånnpump' - Network slow or circle offline - Retry receive ...
2018-10-24 22:40:17,206 - pw-logger - DEBUG - Received an error status '00E1' from circle 'Bruånnpump' - Network slow or circle offline - Retry receive ...
2018-10-24 22:40:43,135 - pw-logger - DEBUG - Received an error status '00E1' from circle 'Bruännpump' - Network slow or circle offline - Retry receive ...
2018-10-24 22:41:14,328 - pw-logger - DEBUG - Received an error status '00E1' from circle 'Bruönnpump' - Network slow or circle offline - Retry receive ...
2018-10-24 22:42:00,715 - pw-logger - DEBUG - Received an error status '00E1' from circle 'BruÅnnpump' - Network slow or circle offline - Retry receive ...
2018-10-24 22:42:46,742 - pw-logger - DEBUG - Received an error status '00E1' from circle 'BruÄnnpump' - Network slow or circle offline - Retry receive ...
2018-10-24 22:43:18,654 - pw-logger - DEBUG - Received an error status '00E1' from circle 'BruÖnnpump' - Network slow or circle offline - Retry receive ...

```

**Comment by SevenW** [comment]
Yes. Line 175 is no longer needed as it is now performed in the constructor of the circle itself. The line 2 can better stay there. If this runs well for a while I will make the update to github.

**Comment by MagnusThome** [comment]
You already added this fix to the code https://github.com/SevenW/Plugwise-2-py/issues/49 ?

**Comment by MagnusThome** [comment]
Letting it run now. Lookin good.

**Comment by SevenW** [comment]
... and that is an interesting observation.
The OFFLINE during initialization was probably caused by the explicit conversion from a unicode exception reason to a str (byte str):
`error("OFFLINE Circle '%s' during initialization Error: %s" % (self.attr['name'], str(reason)))`

So only removing str() around reason might also be an effective fix.

However, then I do not understand the "Error in ten_seconds", as there is no str() involved.

**Comment by SevenW** [comment]
Thanks for reminding me on issue #49. That was really tricky.

**Comment by MagnusThome** [comment]
Still running without any issues :-)

**Comment by SevenW** [comment]
Finally pushed the solution to github. See https://github.com/SevenW/Plugwise-2-py/commit/a97ab1eea9830ced66f269a84ad80bfeb434067a.

**Comment by MagnusThome** [comment]
Super!
