### ISSUE TITLE
Hangups in WebServer

### ISSUE THREAD

**Issue by SevenW** [SevenW/Plugwise-2-py#6]
Still observing hangups in the webserver.

Tracing the code brings me to socket.accept() in SocketServer

```
def get_request(self):
        """Get the request and client address from the socket.

        May be overridden.

        """
        return self.socket.accept()
```

Hangups occur after about 4 days, so investigations are slow.

**Comment by frankhommers** [comment]
Is it correct that this one is still open? Would it be an idea to implement a watchdog script to auto restart the webserver...?

**Comment by SevenW** [comment]
I have not observed this for about a year. I expect that it is hardware specific, and maybe only occured on my Odroid-XU, which I replaced with a Odroid-XU4. I consider it closed
