### ISSUE TITLE
How does always_on in pw-conf.json work?

### ISSUE THREAD

**Issue by MagnusThome** [SevenW/Plugwise-2-py#61]
If I change always_on from False to True on a circle I get a crash on startup. 

So I guess this is a "read only" setting that needs to match how a circle was set up in Plugwise source rather than a setting I can set to either mode in pw-conf.json to change how a circle works?

(I guess it's used in P2py to show the lock on the web page and disable the web page switch?)

**Comment by SevenW** [comment]
This ended up in my junk mail folder. The always_on setting should actually work. It is not only intended for the web ui. It is implemented in api.py and prevents a switch command being performed, if it gets called. I implemented this to prevent to switch off my pv solar panels, while the circle is intended to measure production.

If it crashes, please share the logfiles.

**Comment by MagnusThome** [comment]
I might have figured out when it crashes. It's setting a plug to always on when it's in off state.

This happens:

```
Nov 05 23:03:57 debianlandet python[15641]:   File "/home/sommar/Plugwise-2-py/plugwise/api.py", line 391, in __init__
Nov 05 23:03:57 debianlandet python[15641]:     self.reinit()
Nov 05 23:03:57 debianlandet python[15641]:   File "/home/sommar/Plugwise-2-py/plugwise/api.py", line 401, in reinit
Nov 05 23:03:57 debianlandet python[15641]:     self._get_interval()
Nov 05 23:03:57 debianlandet python[15641]:   File "/home/sommar/Plugwise-2-py/plugwise/api.py", line 946, in _get_interval
Nov 05 23:03:57 debianlandet python[15641]:     cur_idx = info['last_logaddr']
Nov 05 23:03:57 debianlandet python[15641]: TypeError: 'bool' object has no attribute '__getitem__'
Nov 05 23:03:57 debianlandet systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 23:03:57 debianlandet systemd[1]: plugwise.service: Unit entered failed state.
Nov 05 23:03:57 debianlandet systemd[1]: plugwise.service: Failed with result 'exit-code'.

```
