### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by dirixmjm** [SevenW/Plugwise-2-py#63]
Should plugwise-2-py work with python3? 
Or is only python2 supported?

**Comment by SevenW** [comment]
Only V2. Although supporting v3 is om nu list

Verstuurd vanaf mijn iPhone

**Comment by SevenW** [comment]
It has been a while but I am giving it a shot now.

**Comment by SevenW** [comment]
Implemented #74 
The final Python 2.7 version can be obtained with tag v1.1
