### ISSUE TITLE
incompatible with Domoticz 4.x  for new users

### ISSUE THREAD

**Issue by bstrijker** [SevenW/Plugwise-2-py#66]
node-red command sent to Domoticz seems invallid nowadays.

the command in "Plugwise2 Energy to Domoticz" node in the flow:
///json.htm?type=command&param=udevice&hid=$HID&did=$DID&dunit=$DUNIT&dtype=$DTYPE&dsubtype=$DSUBTYPE&nvalue=$NVALUE&svalue=$SVALUE"

substituted: 
http://192.168.1.199:8080/json.htm?type=command&param=udevice&hid=1&did=B29C1C91&dunit=1&dtype=17&dsubtype=0&nvalue=1&svalue=15

returns "Err" by Domoticz. 

The device is not added to domoticz; so all else fails...

**Comment by knielen** [comment]
In the global context you need to change 'udevice&hid' to 'udevice&idx'

**Comment by SevenW** [comment]
Merged #69
