### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by tichkenbrood** [SevenW/Plugwise-2-py#68]
Hi i try to use Plugwise-2-py but i have allays this error. (raspberrypi 3b+)
any idea?

pi@raspberrypi://home/pi/Plugwise-2-py $ sudo python Plugwise-2.py rsync -aXuq /home/pi/datalog/2019/pwact/pwact-2019-04-27*.log /tmp/2019/pwact/
rsync: link_stat "/home/pi/datalog/2019/pwact/pwact-2019-04-27*.log" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Traceback (most recent call last):
  File "Plugwise-2.py", line 1467, in <module>
    main=PWControl()
  File "Plugwise-2.py", line 126, in __init__
    self.device = Stick(port, timeout=1)
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 60, in __init__
    self.init()
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 66, in init
    resp = self.expect_response(PlugwiseStatusResponse)
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 186, in expect_response
    msg = self._recv_response(retry_timeout)
  File "/home/pi/Plugwise-2-py/plugwise/api.py", line 142, in _recv_response
    raise TimeoutException("Timeout while waiting for response from device")
plugwise.exceptions.TimeoutException: Timeout while waiting for response from device

**Comment by tichkenbrood** [comment]
It's fine, I found the problem, thanks for the amazing job! It work prefect

**Comment by DaveDavenport** [comment]
@tichkenbrood What was it? I have same issue (permission on usb device is ok.)

**Comment by tichkenbrood** [comment]
Start the who scripts not only the web

**Comment by tichkenbrood** [comment]
Two*

**Comment by DaveDavenport** [comment]
Enabled some debug, it seems to talk to stick but give sequence errors:
```
out of sequence: 'expected command ack from stick. received message with seqnr 000D - this may be a duplicate message'
```
never receives a correct msg  it seems.

**Comment by SevenW** [comment]
In really bad networks the code may have been not so robust. The Stick itself seems to pile up messages that the python script is not reading out. Improved in the latest python3 version
