### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by dorenberg** [SevenW/Plugwise-2-py#7]
Hello SevenW,

I have followed your wiki in installing the application on my raspberry, but it seems that I cannot see the webserver. I am seeing the following error. I configured the files but it seems that I cannot start it?

I you could provide some kind of guidance that would be great. The ultimate goal is to connect my circles via MQTT into domoticz. 

nohup: ignoring input and redirecting stderr to stdout

**Comment by SevenW** [comment]
I am also interested in connecting to domoticz, so keep me posted on your findings.

The message you see is always given by nohup and is not an error. To see whether Plugwise-2.py and Plugwise-2-web.py are running (and not crashed) use:
ps -AF | grep Plug
you should see both processes.
If not, the crash stackdump is in:/tmp/pwput.log and /tmp/pwwebout.log (from the command lines you used to start).

To see whether the programs are doing work you could tail the log files. For example:
tail -f /var/log/pw-logger.log

The past week I have been working on the master branch, without proper testing. So it could be that I have broken something in Plugwise-2.py. Please report and I will fix.

SevenW

**Comment by dorenberg** [comment]
I will continue this evening with your suggestion.

this is what I see when executing the scripts. Maybe there is something wrong in the config files? How can I double check my circle+ and circles MAC addresses?

pi@raspberrypi ~ $ nohup python Plugwise-2.py >>/tmp/pwout.log&
[2] 19814
[1] Exit 1 nohup python Plugwise-2.py >> /tmp/pwout/log
pi@raspberrypi ~ $ nohup: ignoring input and redirecting stderr to stdout

rsync: link_stat "/home/pi/datalog/2015/pwact/pwact-2015-07-23*.log" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
Traceback (most recent call last):
File "Plugwise-2.py", line 1306, in <module>
main=PWControl()
File "Plugwise-2.py", line 151, in __init__
sconf = json.load(open(self.staticconfig_fn))
File "/usr/lib/python2.7/json/__init__.py", line 278, in load
**kw)
File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

python Plugwise-2-web.py 8000 secure >>pwwebout.log
Traceback (most recent call last):
File "Plugwise-2-web.py", line 343, in <module>
main()
File "Plugwise-2-web.py", line 325, in main
ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
AttributeError: 'module' object has no attribute 'create_default_context'

**Comment by SevenW** [comment]
The first problem is that "pw-conf.json" is not formatted as a proper json file. The program aborts/crashed there.
So you have to carefully inspect this file. Make sure that all strings are in double quotes, check the comma's, and the array brackets [] and {}.
Actually it is nicer to use a JSON validator, such as http://jsonlint.com/
If this is not helping, you can try to mail me your config files. User info at the domain name of my website without the w w w .

The second error with the web app seems to be related to SSL and may be a configuration issue on the raspi. I am not sure. For the moment you can work around it by not using ssl (remove secure from command line) and not opening the 8000 port to the internet.

**Comment by SevenW** [comment]
After proper configuration the problems did not recur.
