### ISSUE TITLE
Support MQTT with username password

### ISSUE THREAD

**Issue by gruijter** [SevenW/Plugwise-2-py#70]
Is there a way to use an MQTT server that requires username/password?

(And any news on updating the code to Python 3 maybe?)

THX!

**Comment by Mediacj** [comment]
You can add it to pw-hostconfig.json with this parameters:
"mqtt_ip": "MQTT_IP_ADDRESS", "mqtt_port": "1883", "mqtt_user": "USER", "mqtt_password": "PASSWORD"
It has been prepared in the source but not documented so far I can see.
