### ISSUE TITLE
with Production enabled some circles produce double MQTT messages and stop logging to file after a while

### ISSUE THREAD

**Issue by SevenW** [SevenW/Plugwise-2-py#75]
This issue has been mentioned before, but I can't retrace it.

The root cause is that when changing a circle from its default recording of only consumption to both consumption and production it seemingly depends on the state of the circle when the new configuration is applied. The historic log buffers have four readings per index. The expected layout is:
```
timestamp1 consumption1
timestamp1 production1
timestamp2 consumption2
timestamp2 production2
```
However now observed after replacing a defect circle with my solar panels the the order is:
```
timestamp1 production1
timestamp2 consumption2
timestamp2 production2
timestamp3 consumption3
```
So shifted by one slot per index to be read.

Symptoms are:
per timestamp-n recording two entries in the pwlog logfiles and also two MQTT messages with the same timestamp. The second line always has read-out values of zero, while the other shows the actual readings.

Finally when the historic buffer wraps around and starts at index zero again, Plugwise-2.py is not handling this well and keeps reading the highest index, and never makes the step to index zero again, effectively stop writing logfiles and sending MQTT messages. of type plugwise2py/energy

Looking at the code it is really difficult and risky to improve the logic to detect this shifted by one situation. Therefore I explored another option. I figured out the command to instruct a circle to reset thw log index to zero, and this does the trick. The circle is working as expected.

A new reset type function is added to the api and protocol and I will publish a code snippet or better an offline tool to preform this reset.

**Comment by Mediacj** [comment]
After installing this new version it also solved the same problem with my production solar-panels circle. Thanks!

**Comment by Mediacj** [comment]
I have the same symptom again but it doesn't get fixed. Did you release an offline tool to repair it?
