### ISSUE TITLE
Add Plugwise Stretch and Smile?

### ISSUE THREAD

**Issue by xander2k** [SevenW/Plugwise-2-py#8]
Hi,

is it possible to add plugwise stretch and/or smile trough ip to the system?

Also the question, if it is possible to use plugwise source through MQTT Interface?

thx

**Comment by SevenW** [comment]
Stretch and Smile are not supported. Plugwise-2-py is intend to operate with the (usb) Stick, without the need to run Source on a Windows PC.

Stretch, Smile and Source have HTTP-API's. I do not know whether they are open, or that they are known by reverse engineering. Googling gives some results. Undoubtedly there is more:

http://www.domoticz.com/forum/viewtopic.php?f=31&t=600&hilit=plugwise
http://domoticx.com/plugwise-stretch-2-0-http-api-en-schakelen-met-scripts/

Also Source does not talk by itself with MQTT. There needs to be an active program in between Source and MQTT, which reads Source (or Stretch or Smile) and posts to MQTT. Search the internet, to see whether this is already solved by someone.

SevenW
